"use client";

import { useEffect, useState, useTransition, type ReactNode } from "react";
import {
  addCommitmentAction,
  addGoalAction,
  generateAdviceAction,
  getMoneyPlanAction,
  removeCommitmentAction,
  removeGoalAction,
  resetMonthPlanAction,
  saveMoneyProfileAction,
  setMonthBudgetAction,
  updateGoalSavedAction,
  type MoneyPlanView,
} from "@/app/money/actions";
import { LoadingBlock } from "@/components/LoadingSpinner";
import { useI18n } from "@/lib/i18n/LocaleProvider";
import type { CommitmentKind } from "@/generated/prisma/client";

/**
 * Planning, rather than recording.
 *
 * The rest of the money screen is about what happened. This is about what
 * is going to: income minus what is already promised, minus what is being
 * saved, is what there is to live on — and that subtraction, not a number
 * typed from memory, is where a budget should come from.
 *
 * Nothing here is generated by a model except the weekly advice, and that
 * is given the arithmetic already done. Which month falls short, and by
 * how much, is subtraction; only "which three lines could come down" is
 * judgement.
 */
export function MoneyPlanPanel({
  todayKey,
  /** Bumped by the screen when something outside this panel changed the
   * month's spending (a statement import), so the used amounts re-read. */
  version = 0,
}: {
  todayKey: string;
  version?: number;
}) {
  const { t } = useI18n();
  const [data, setData] = useState<MoneyPlanView | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [pending, startPending] = useTransition();
  const [asking, startAsking] = useTransition();

  useEffect(() => {
    getMoneyPlanAction(todayKey).then(setData);
  }, [todayKey, version]);

  if (!data) return <LoadingBlock label={t.common.loading} />;

  /** Every mutation returns the whole picture, because changing one
   * number moves the rest of it. */
  function run(action: () => Promise<MoneyPlanView | { error: string }>) {
    startPending(async () => {
      const res = await action();
      if ("error" in res) {
        setError(res.error);
        return;
      }
      setError(null);
      setData(res);
    });
  }

  const { plan, profile, year, commitments, goals, advice, spentByCategory } = data;
  const allocated = plan.budgets.reduce((sum, b) => sum + b.amountYen, 0);
  const unallocated = plan.projection.discretionaryYen - allocated;
  const shortMonths = year.filter((m) => m.belowMinimum);
  // How far through the month today is, so each bar can be read against
  // the calendar and not only against its ceiling: two thirds of a budget
  // used is fine on the 20th and a problem on the 8th.
  const [yearNum, monthNum, dayNum] = todayKey.split("-").map(Number);
  const monthProgress = dayNum / new Date(Date.UTC(yearNum, monthNum, 0)).getUTCDate();
  // Spending in a category the plan has no line for — a category added
  // after the plan was made, or one the allocation left out. Listed so
  // the money shows up somewhere, with a box to give it a budget.
  const planned = new Set(plan.budgets.map((b) => b.category));
  const unplanned = Object.entries(spentByCategory)
    .filter(([category, spent]) => !planned.has(category) && spent > 0)
    .sort((a, b) => b[1] - a[1]);

  return (
    <div className="flex flex-col gap-6">
      {error && <p className="rounded-lg bg-accent-soft px-3 py-2 text-xs whitespace-pre-line text-accent">{error}</p>}

      {/* ① 手取りと前提 */}
      <Section heading={t.money.planHeading} note={t.money.planIntro}>
        <div className="grid grid-cols-3 gap-3">
          {(
            [
              ["monthlyIncomeYen", t.money.income],
              ["minimumLivingYen", t.money.minimumLiving],
              ["bufferYen", t.money.buffer],
            ] as const
          ).map(([key, label]) => (
            <Field key={key} label={label}>
              <input
                defaultValue={profile[key]}
                onBlur={(e) =>
                  run(() =>
                    saveMoneyProfileAction(
                      {
                        monthlyIncomeYen: profile.monthlyIncomeYen,
                        minimumLivingYen: profile.minimumLivingYen,
                        bufferYen: profile.bufferYen,
                        [key]: Number(e.target.value.replace(/[,¥\s]/g, "")),
                      },
                      todayKey,
                    ),
                  )
                }
                inputMode="numeric"
                className="w-full bg-transparent text-xs text-ink focus:outline-none"
              />
            </Field>
          ))}
        </div>

        <div className="flex flex-wrap items-baseline gap-x-5 gap-y-1 border-t border-line pt-2.5">
          <Figure label={t.money.colIncome} yen={plan.projection.incomeYen} />
          <Figure label={t.money.colCommitment} yen={plan.projection.commitmentYen === 0 ? 0 : -plan.projection.commitmentYen} />
          <Figure label={t.money.colSaving} yen={plan.projection.savingYen === 0 ? 0 : -plan.projection.savingYen} />
          <Figure label={t.money.buffer} yen={plan.projection.bufferYen === 0 ? 0 : -plan.projection.bufferYen} />
          <Figure label={t.money.colLiving} yen={plan.projection.discretionaryYen} strong tone={plan.projection.belowMinimum ? "warn" : "plain"} />
        </div>
        {plan.justCreated && <p className="font-mono text-[10px] text-accent">{t.money.planJustCreated}</p>}
      </Section>

      {/* ② カテゴリ別の配分 */}
      <Section
        heading={t.money.monthPlanHeading}
        right={
          <button
            onClick={() => run(() => resetMonthPlanAction(plan.month, todayKey))}
            disabled={pending}
            className="rounded-full border border-line-strong px-3 py-1 font-mono text-[10px] text-ink-soft hover:border-accent hover:text-accent disabled:opacity-50"
          >
            {t.money.planReset}
          </button>
        }
      >
        <ul className="flex flex-col gap-2.5">
          {plan.budgets.map((b) => (
            <BudgetRow
              key={b.category}
              category={b.category}
              spentYen={spentByCategory[b.category] ?? 0}
              budgetYen={b.amountYen}
              monthProgress={monthProgress}
              onSave={(value) => run(() => setMonthBudgetAction(plan.month, b.category, value ?? 0, todayKey))}
            />
          ))}
          {unplanned.map(([category, spent]) => (
            <BudgetRow
              key={category}
              category={category}
              spentYen={spent}
              budgetYen={null}
              monthProgress={monthProgress}
              onSave={(value) => value !== null && run(() => setMonthBudgetAction(plan.month, category, value, todayKey))}
            />
          ))}
        </ul>
        <p className={`font-mono text-[10px] ${unallocated < 0 ? "text-accent" : "text-ink-faint"}`}>
          {t.money.monthPlanLeft(unallocated)}
        </p>
        <p className="font-mono text-[9px] leading-relaxed text-ink-faint">{t.money.paceNote}</p>
      </Section>

      {/* ③ 固定費・分割払い */}
      <Section heading={t.money.commitmentsHeading} note={t.money.commitmentsIntro}>
        <ul className="flex flex-col gap-1">
          {commitments.map((c) => (
            <li key={c.id} className="group flex items-baseline gap-2">
              <span className="rounded bg-surface-alt px-1.5 py-0.5 font-mono text-[9px] text-ink-soft">{kindLabel(c.kind, t)}</span>
              <span className="min-w-0 flex-1 truncate text-[11.5px] text-ink">{c.name}</span>
              <span className="font-mono text-[9px] text-ink-faint">
                {c.fromMonth}〜{c.toMonth ?? ""}
              </span>
              <span className="font-mono text-[11px] text-ink">¥{c.monthlyYen.toLocaleString()}</span>
              <button
                onClick={() => run(() => removeCommitmentAction(c.id, todayKey))}
                className="font-mono text-[9px] text-ink-faint opacity-0 transition-opacity group-hover:opacity-100 hover:text-accent"
              >
                {t.common.delete}
              </button>
            </li>
          ))}
        </ul>
        <CommitmentForm month={plan.month} onSubmit={(input) => run(() => addCommitmentAction(input, todayKey))} pending={pending} />
      </Section>

      {/* ④ 貯金の目標 */}
      <Section heading={t.money.goalsHeading} note={t.money.goalsIntro}>
        <ul className="flex flex-col gap-1">
          {goals.map((g) => {
            const contribution = plan.projection.goals.find((x) => x.name === g.name);
            return (
              <li key={g.id} className="group flex items-baseline gap-2">
                <span className="min-w-0 flex-1 truncate text-[11.5px] text-ink">{g.name}</span>
                <span className="font-mono text-[9px] text-ink-faint">{g.targetMonth}</span>
                <input
                  defaultValue={g.savedYen}
                  onBlur={(e) => run(() => updateGoalSavedAction(g.id, Number(e.target.value.replace(/[,¥\s]/g, "")), todayKey))}
                  inputMode="numeric"
                  className="w-20 rounded border border-line bg-surface px-1.5 py-0.5 text-right font-mono text-[10px] text-ink-soft focus:border-accent focus:outline-none"
                />
                <span className="font-mono text-[9.5px] text-ink-faint">/ ¥{g.targetYen.toLocaleString()}</span>
                <span className={`font-mono text-[11px] ${contribution?.overdue ? "text-accent" : "text-ink"}`}>
                  {contribution?.overdue ? t.money.goalOverdue : `+¥${(contribution?.yen ?? 0).toLocaleString()}`}
                </span>
                <button
                  onClick={() => run(() => removeGoalAction(g.id, todayKey))}
                  className="font-mono text-[9px] text-ink-faint opacity-0 transition-opacity group-hover:opacity-100 hover:text-accent"
                >
                  {t.common.delete}
                </button>
              </li>
            );
          })}
        </ul>
        <GoalForm month={plan.month} onSubmit={(input) => run(() => addGoalAction(input, todayKey))} pending={pending} />
      </Section>

      {/* ⑤ 1年の見通し */}
      <Section heading={t.money.yearHeading} note={t.money.yearIntro}>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[460px] border-collapse">
            <thead>
              <tr className="font-mono text-[9px] tracking-wider text-ink-faint uppercase">
                <th className="py-1 text-left font-normal">—</th>
                <th className="py-1 text-right font-normal">{t.money.colCommitment}</th>
                <th className="py-1 text-right font-normal">{t.money.colSaving}</th>
                <th className="py-1 text-right font-normal">{t.money.colLiving}</th>
              </tr>
            </thead>
            <tbody>
              {year.map((m) => (
                <tr key={m.month} className="border-t border-line">
                  <td className="py-1 font-mono text-[10px] text-ink-soft">{m.month}</td>
                  <td className="py-1 text-right font-mono text-[10.5px] text-ink-soft">¥{m.commitmentYen.toLocaleString()}</td>
                  <td className="py-1 text-right font-mono text-[10.5px] text-ink-soft">¥{m.savingYen.toLocaleString()}</td>
                  <td className={`py-1 text-right font-mono text-[10.5px] font-semibold ${m.belowMinimum ? "text-accent" : "text-ink"}`}>
                    ¥{m.discretionaryYen.toLocaleString()}
                    {m.belowMinimum && <span className="ml-1 text-[9px]">{t.money.belowMinimum}</span>}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {shortMonths.length > 0 && <p className="text-[11px] leading-relaxed text-accent">{t.money.belowMinimumNote}</p>}
      </Section>

      {/* ⑥ 今週の会計士 */}
      <Section
        heading={t.money.adviceHeading}
        note={t.money.adviceIntro}
        right={
          <button
            onClick={() =>
              startAsking(async () => {
                const res = await generateAdviceAction(todayKey);
                if ("error" in res) setError(res.error);
                else {
                  setError(null);
                  setData(res);
                }
              })
            }
            disabled={asking}
            className="btn-sheen rounded-full bg-accent px-3.5 py-1.5 font-mono text-[10.5px] font-semibold text-on-accent disabled:opacity-50"
          >
            {asking ? t.money.adviceAsking : t.money.adviceAsk}
          </button>
        }
      >
        {!advice ? (
          <p className="font-mono text-[10.5px] text-ink-faint">{t.money.adviceNone}</p>
        ) : (
          <>
            <p className="font-mono text-[9px] text-ink-faint">{t.money.adviceWeek(advice.weekStartDateKey, todayKey)}</p>
            <p className="text-[11.5px] leading-relaxed text-ink">{advice.summary}</p>
            <ul className="flex flex-col gap-1.5">
              {advice.actions.map((a, i) => (
                <li key={`${a.category}-${i}`} className="flex items-baseline gap-2">
                  <span className="rounded bg-surface-alt px-1.5 py-0.5 font-mono text-[9px] text-ink-soft">{a.category}</span>
                  <span className="min-w-0 flex-1 text-[11.5px] text-ink">{a.action}</span>
                  <span className="font-mono text-[10.5px] text-accent">{t.money.adviceSaving(a.monthlySavingYen)}</span>
                </li>
              ))}
            </ul>
            {advice.actions.length > 0 && (
              <p className="font-mono text-[10px] text-ink-soft">
                {t.money.adviceTotal(advice.actions.reduce((sum, a) => sum + a.monthlySavingYen, 0))}
              </p>
            )}
          </>
        )}
      </Section>
    </div>
  );
}

function kindLabel(kind: CommitmentKind, t: ReturnType<typeof useI18n>["t"]): string {
  return kind === "INSTALMENT" ? t.money.kindInstalment : kind === "SUBSCRIPTION" ? t.money.kindSubscription : t.money.kindFixed;
}

function CommitmentForm({
  month,
  onSubmit,
  pending,
}: {
  month: string;
  onSubmit: (input: { name: string; kind: CommitmentKind; monthlyYen: number; fromMonth: string; toMonth: string | null }) => void;
  pending: boolean;
}) {
  const { t } = useI18n();
  const [name, setName] = useState("");
  const [kind, setKind] = useState<CommitmentKind>("FIXED");
  const [amount, setAmount] = useState("");
  const [from, setFrom] = useState(month);
  const [to, setTo] = useState("");

  return (
    <div className="flex flex-wrap items-center gap-1.5 border-t border-line pt-2.5">
      <input
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder={t.money.namePlaceholder}
        className="min-w-0 flex-1 rounded-md border border-line bg-surface px-2 py-1 text-[11px] text-ink focus:border-accent focus:outline-none"
      />
      <select
        value={kind}
        onChange={(e) => setKind(e.target.value as CommitmentKind)}
        className="rounded-md border border-line bg-surface px-1.5 py-1 text-[11px] text-ink focus:outline-none"
      >
        <option value="FIXED">{t.money.kindFixed}</option>
        <option value="SUBSCRIPTION">{t.money.kindSubscription}</option>
        <option value="INSTALMENT">{t.money.kindInstalment}</option>
      </select>
      <input
        value={amount}
        onChange={(e) => setAmount(e.target.value)}
        inputMode="numeric"
        placeholder="¥"
        className="w-20 rounded-md border border-line bg-surface px-2 py-1 text-right font-mono text-[10.5px] text-ink focus:border-accent focus:outline-none"
      />
      <input
        type="month"
        value={from}
        onChange={(e) => setFrom(e.target.value)}
        aria-label={t.money.fromMonth}
        className="rounded-md border border-line bg-surface px-1.5 py-1 font-mono text-[10px] text-ink focus:outline-none"
      />
      <input
        type="month"
        value={to}
        onChange={(e) => setTo(e.target.value)}
        aria-label={t.money.toMonth}
        placeholder={t.money.toMonthOpen}
        className="rounded-md border border-line bg-surface px-1.5 py-1 font-mono text-[10px] text-ink focus:outline-none"
      />
      <button
        onClick={() => {
          if (!name.trim() || !amount) return;
          onSubmit({
            name,
            kind,
            monthlyYen: Number(amount.replace(/[,¥\s]/g, "")),
            fromMonth: from,
            toMonth: to || null,
          });
          setName("");
          setAmount("");
          setTo("");
        }}
        disabled={pending || !name.trim() || !amount}
        className="btn-sheen rounded-md bg-accent px-2.5 py-1 font-mono text-[10px] font-semibold text-on-accent disabled:opacity-40"
      >
        {t.common.add}
      </button>
    </div>
  );
}

function GoalForm({
  month,
  onSubmit,
  pending,
}: {
  month: string;
  onSubmit: (input: { name: string; targetYen: number; targetMonth: string; savedYen: number }) => void;
  pending: boolean;
}) {
  const { t } = useI18n();
  const [name, setName] = useState("");
  const [target, setTarget] = useState("");
  const [by, setBy] = useState(month);
  const [saved, setSaved] = useState("");

  return (
    <div className="flex flex-wrap items-center gap-1.5 border-t border-line pt-2.5">
      <input
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder={t.money.namePlaceholder}
        className="min-w-0 flex-1 rounded-md border border-line bg-surface px-2 py-1 text-[11px] text-ink focus:border-accent focus:outline-none"
      />
      <input
        value={target}
        onChange={(e) => setTarget(e.target.value)}
        inputMode="numeric"
        aria-label={t.money.goalTarget}
        placeholder="¥"
        className="w-24 rounded-md border border-line bg-surface px-2 py-1 text-right font-mono text-[10.5px] text-ink focus:border-accent focus:outline-none"
      />
      <input
        type="month"
        value={by}
        onChange={(e) => setBy(e.target.value)}
        aria-label={t.money.goalByMonth}
        className="rounded-md border border-line bg-surface px-1.5 py-1 font-mono text-[10px] text-ink focus:outline-none"
      />
      <input
        value={saved}
        onChange={(e) => setSaved(e.target.value)}
        inputMode="numeric"
        aria-label={t.money.goalSaved}
        placeholder={t.money.goalSaved}
        className="w-20 rounded-md border border-line bg-surface px-2 py-1 text-right font-mono text-[10.5px] text-ink focus:border-accent focus:outline-none"
      />
      <button
        onClick={() => {
          if (!name.trim() || !target) return;
          onSubmit({
            name,
            targetYen: Number(target.replace(/[,¥\s]/g, "")),
            targetMonth: by,
            savedYen: Number((saved || "0").replace(/[,¥\s]/g, "")),
          });
          setName("");
          setTarget("");
          setSaved("");
        }}
        disabled={pending || !name.trim() || !target}
        className="btn-sheen rounded-md bg-accent px-2.5 py-1 font-mono text-[10px] font-semibold text-on-accent disabled:opacity-40"
      >
        {t.common.add}
      </button>
    </div>
  );
}

function Section({
  heading,
  note,
  right,
  children,
}: {
  heading: string;
  note?: string;
  right?: ReactNode;
  children: ReactNode;
}) {
  return (
    <section className="flex flex-col gap-2.5 rounded-xl border border-line bg-surface p-4">
      <div className="flex flex-wrap items-center gap-3">
        <p className="font-mono text-[9.5px] tracking-wider text-ink-faint uppercase">{heading}</p>
        {right && <span className="ml-auto">{right}</span>}
      </div>
      {note && <p className="text-[11px] leading-relaxed text-ink-soft">{note}</p>}
      {children}
    </section>
  );
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <label className="flex flex-col gap-1">
      <span className="font-mono text-[9px] tracking-wider text-ink-faint uppercase">{label}</span>
      <span className="rounded-md border border-line bg-surface px-2.5 py-1.5">{children}</span>
    </label>
  );
}

function Figure({ label, yen, strong, tone }: { label: string; yen: number; strong?: boolean; tone?: "plain" | "warn" }) {
  // Negating zero prints "-0", which reads like a rounding bug.
  const value = yen === 0 ? 0 : yen;
  return (
    <span className="flex flex-col gap-0.5">
      <span className="font-mono text-[9px] tracking-wider text-ink-faint uppercase">{label}</span>
      <span className={`font-mono ${strong ? "text-[13px] font-bold" : "text-[11px]"} ${tone === "warn" ? "text-accent" : "text-ink"}`}>
        ¥{value.toLocaleString()}
      </span>
    </span>
  );
}

/**
 * One category of the month: used so far against its budget, and where
 * the month is.
 *
 * Over the budget and on pace to go over are different situations and get
 * different words — one has already happened, the other is still a choice.
 * `budgetYen` null is a category with spending but no line in the plan.
 */
function BudgetRow({
  category,
  spentYen,
  budgetYen,
  monthProgress,
  onSave,
}: {
  category: string;
  spentYen: number;
  budgetYen: number | null;
  monthProgress: number;
  /** null when the box was left empty. */
  onSave: (value: number | null) => void;
}) {
  const { t } = useI18n();
  // A ¥0 budget with spending against it is simply over — drawn as a full
  // bar, not as an empty one next to the word 予算超過.
  const ratio =
    budgetYen === null ? null : budgetYen > 0 ? spentYen / budgetYen : spentYen > 0 ? Number.POSITIVE_INFINITY : null;
  const over = budgetYen !== null && spentYen > budgetYen;
  const aheadOfPace = ratio !== null && !over && ratio > monthProgress + 0.1;
  return (
    <li className="flex flex-col gap-1">
      <div className="flex items-baseline gap-2">
        <span className="text-xs text-ink">{category}</span>
        {over && <span className="font-mono text-[9px] text-accent">{t.money.overBudget}</span>}
        {aheadOfPace && <span className="font-mono text-[9px] text-ink-soft">{t.money.aheadOfPace}</span>}
        <span className="ml-auto font-mono text-[11px] text-ink">¥{spentYen.toLocaleString()}</span>
        <span className="font-mono text-[9.5px] text-ink-faint">/</span>
        <input
          defaultValue={budgetYen ?? ""}
          placeholder={t.money.noBudget}
          onBlur={(e) => {
            const text = e.target.value.replace(/[,¥\s]/g, "");
            if (text === "") return onSave(null);
            const value = Number(text);
            if (Number.isFinite(value)) onSave(value);
          }}
          inputMode="numeric"
          className="w-20 rounded border border-line bg-surface px-1.5 py-0.5 text-right font-mono text-[10px] text-ink-soft focus:border-accent focus:outline-none"
        />
      </div>
      <div className="relative h-1.5 overflow-hidden rounded-full bg-surface-alt">
        {ratio !== null && (
          <div
            className={`h-full rounded-full ${over ? "bg-accent" : "bg-[var(--color-meal)]"}`}
            style={{ width: `${Math.min(ratio, 1) * 100}%` }}
          />
        )}
        {budgetYen !== null && (
          <div className="absolute top-0 h-full w-px bg-ink-faint" style={{ left: `${monthProgress * 100}%` }} />
        )}
      </div>
    </li>
  );
}
